version: "3.7"
services:
  backend:
    container_name: se214_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - bck

networks:
  bck:
    driver: bridge
